#!/bin/bash

# ANSI escapes
RED='\033[31m'
GREEN='\033[32m'
BOLD='\033[1m'
ITALIC='\033[3m'
STRIKETHROUGH='\033[9m'
RESET='\033[0m'

# usage: repeat character number
# example: repeat = 10
# output: ==========
repeat() {
  for ((i = 1; i < $2; i++)); do
    echo -n "$1"
  done
}

# usage: step text command
# example: step "echoing hey" "echo hey"
# output:
# echoing hey...
# hey
# echoing hey... done!
# ====================
step() {
  echo -e "${BOLD}$1${RESET}" &&
    eval "$2"

  if [ "${PIPESTATUS[0]}" -gt 0 ]; then
    echo -e "${RED}${ITALIC}${STRIKETHROUGH}$1${RESET}${RED} error!${RESET}" &&
      exit 1
  else
    TEXT="${GREEN}${ITALIC}${STRIKETHROUGH}$1${RESET}${GREEN} done!${RESET}"
    echo -e "$TEXT"
  fi

  echo -e "${BOLD}$(repeat "=" "$(echo "$TEXT" | sed -E 's/\033[^\\]*m//g' | wc -c)")${RESET}"
}

build() {
  step "Installing kiwi..." "
    dnf --assumeyes install --setopt install_weak_deps=False kiwi kiwi-systemdeps distribution-gpg-keys git
  "

  WORK_DIR_F43="$(mktemp -d --suffix="-fedora-kde-iso-f43")"

  step "Cloning kiwi for f43..." "
    git clone --depth=1 https://pagure.io/fedora-kiwi-descriptions.git -b f43 $WORK_DIR_F43
  "

  WORK_DIR_F44="$(mktemp -d --suffix="-fedora-kde-iso-f44")"

  step "Cloning kiwi for f44..." "
    git clone --depth=1 https://pagure.io/fedora-kiwi-descriptions.git -b f44 $WORK_DIR_F44
  "

  step "Building f43 ISO..." "
    pushd $WORK_DIR_F43
    ./kiwi-build --kiwi-file=Fedora.kiwi --image-type=iso --image-profile=KDE-Desktop-Live --output-dir $WORK_DIR_F43/output/
    popd
  "

  step "Building f44 ISO..." "
    pushd $WORK_DIR_F44
    ./kiwi-build --kiwi-file=Fedora.kiwi --image-type=iso --image-profile=KDE-Desktop-Live --output-dir $WORK_DIR_F44/output/
    popd
  "
  
  # Actual f43 ISO path
  ISO_PATH_F43=$WORK_DIR_F43/output/-build/Fedora.x86_64-43.iso

  # Actual f44 ISO path
  ISO_PATH_F44=$WORK_DIR_F44/output/-build/Fedora.x86_64-44.iso

  step "Generating f43 sha256sum..." "
    sha256sum $ISO_PATH_F43 | head -c 64 >> $WORK_DIR_F43/CHECKSUM_f43.txt
  "

  step "Generating f44 sha256sum..." "
    sha256sum $ISO_PATH_F44 | head -c 64 >> $WORK_DIR_F44/CHECKSUM_f44.txt
  "

  step "Splitting f43 ISO file into smaller ones..." "
    split -b 2000m $ISO_PATH_F43 $WORK_DIR_F43/Fedora.x86_64-43.iso
  "

  step "Splitting f44 ISO file into smaller ones..." "
    split -b 2000m $ISO_PATH_F44 $WORK_DIR_F44/Fedora.x86_64-44.iso
  "

  step "Linking files from tmpfs to disk for uploading..." "
    ln -sf $WORK_DIR_F43/Fedora.x86_64-43.isoaa Fedora.x86_64-43.isoaa 
    ln -sf $WORK_DIR_F43/Fedora.x86_64-43.isoab Fedora.x86_64-43.isoab
    ln -sf $WORK_DIR_F43/CHECKSUM_f43.txt CHECKSUM_f43.txt

    ln -sf $WORK_DIR_F44/Fedora.x86_64-44.isoaa Fedora.x86_64-44.isoaa 
    ln -sf $WORK_DIR_F44/Fedora.x86_64-44.isoab Fedora.x86_64-44.isoab
    ln -sf $WORK_DIR_F44/CHECKSUM_f44.txt CHECKSUM_f44.txt
  "
}

main() {
  if [ -z ${DATE+x} ]; then
    echo -e "${RED}DATE variable not set!${RESET}" &&
      exit 1
  else
    build
  fi
}

main