#!/bin/bash

# ANSI escapes
RED='\033[31m'
GREEN='\033[32m'
BOLD='\033[1m'
ITALIC='\033[3m'
STRIKETHROUGH='\033[9m'
RESET='\033[0m'

# usage: repeat character number
# example: repeat = 10
# output: ==========
repeat() {
  for ((i = 1; i < $2; i++)); do
    echo -n "$1"
  done
}

# usage: step text command
# example: step "echoing hey" "echo hey"
# output:
# echoing hey...
# hey
# echoing hey... done!
# ====================
step() {
  echo -e "${BOLD}$1${RESET}" &&
    eval "$2"

  if [ "${PIPESTATUS[0]}" -gt 0 ]; then
    echo -e "${RED}${ITALIC}${STRIKETHROUGH}$1${RESET}${RED} error!${RESET}" &&
      exit 1
  else
    TEXT="${GREEN}${ITALIC}${STRIKETHROUGH}$1${RESET}${GREEN} done!${RESET}"
    echo -e "$TEXT"
  fi

  echo -e "${BOLD}$(repeat "=" "$(echo "$TEXT" | sed -E 's/\033[^\\]*m//g' | wc -c)")${RESET}"
}

build() {
  step "Installing kiwi..." "
    dnf --assumeyes install kiwi kiwi-systemdeps distribution-gpg-keys git
  "

  WORK_DIR="$(mktemp -d --suffix="-fedora-iso")"

  step "Cloning kiwi..." "
    git clone --depth=1 https://pagure.io/fedora-kiwi-descriptions.git -b f43 $WORK_DIR
  "

  step "Building ISO..." "
    pushd $WORK_DIR/fedora-kiwi-descriptions
    ./kiwi-build --kiwi-file=Fedora.kiwi --image-type=iso --image-profile=KDE-Desktop-Live --output-dir $WORK_DIR/output/
    popd
  "
  
  # Actual ISO path
  ISO_PATH=$WORK_DIR/output/-build/Fedora.x86_64-43.iso

  step "Generating sha256sum text file..." "
    sha256sum $ISO_PATH >> $WORK_DIR/CHECKSUM.txt
  "

  step "Splitting ISO file into smaller ones..." "
    split -b 2000m $ISO_PATH $WORK_DIR/Fedora.x86_64-43.iso
  "

  step "Linking files from tmpfs to disk for uploading..." "
    ln -sf $WORK_DIR/Fedora.x86_64-43.isoaa Fedora.x86_64-43.isoaa 
    ln -sf $WORK_DIR/Fedora.x86_64-43.isoab Fedora.x86_64-43.isoab
    ln -sf $WORK_DIR/CHECKSUM.txt CHECKSUM.txt
  "
}

main() {
  if [ -z ${DATE+x} ]; then
    echo -e "${RED}DATE variable not set!${RESET}" &&
      exit 1
  else
    build
  fi
}

main
