name: Build Fedora 43 & 44 KDE ISO

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      dev:
        description: "Run as development?"
        type: boolean
        required: true
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    permissions:
      contents: write

    container:
      image: fedora:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v6

      - name: Set current date as environment variable
        run: echo "DATE=$(date +'%d.%m.%Y')" >> "$GITHUB_ENV"

      - name: Run build-iso script
        run: bash build-iso

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dev == 'true' }}
        with:
          name: Fedora 43 & 44 KDE ${{ env.DATE }}
          path: |
            Fedora.x86_64-43.isoaa
            Fedora.x86_64-43.isoab
            Fedora.x86_64-44.isoaa
            Fedora.x86_64-44.isoab
            CHECKSUM_f43.txt
            CHECKSUM_f44.txt

      - name: Create tag and release
        uses: softprops/action-gh-release@v3
        if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.dev == 'false') }}
        with:
          name: Fedora 43 & 44 KDE ${{ env.DATE }}
          tag_name: ${{ env.DATE }}
          files: |
            Fedora.x86_64-43.isoaa
            Fedora.x86_64-43.isoab
            Fedora.x86_64-44.isoaa
            Fedora.x86_64-44.isoab
            CHECKSUM_f43.txt
            CHECKSUM_f44.txt